-- MySQL Script generated by MySQL Workbench
-- Thu Apr 11 16:15:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Banco` DEFAULT CHARACTER SET utf8 ;
USE `Banco` ;

-- -----------------------------------------------------
-- Table `Banco`.`Gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco`.`Gerente` (
  `documento` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `codigoAcceso` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`documento`),
  UNIQUE INDEX `documento_UNIQUE` (`documento` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Banco`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco`.`Sucursal` (
  `idSucursal` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `direccion` VARCHAR(60) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `historial` VARCHAR(1000) NOT NULL,
  `balance` INT NOT NULL,
  `gerenteDocumento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idSucursal`),
  UNIQUE INDEX `idSucursal_UNIQUE` (`idSucursal` ASC) ,
  INDEX `fk_Sucursal_Gerente1_idx` (`gerenteDocumento` ASC) ,
  CONSTRAINT `fk_Sucursal_Gerente1`
    FOREIGN KEY (`gerenteDocumento`)
    REFERENCES `Banco`.`Gerente` (`documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Banco`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco`.`Vendedor` (
  `documento` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `codigoAcceso` VARCHAR(255) NOT NULL,
  `idSucursal` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`documento`),
  UNIQUE INDEX `documento_UNIQUE` (`documento` ASC) ,
  INDEX `fk_Vendedor_Sucursal1_idx` (`idSucursal` ASC) ,
  CONSTRAINT `fk_Vendedor_Sucursal1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `Banco`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Banco`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco`.`Cliente` (
  `documento` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `idSucursales` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`documento`),
  UNIQUE INDEX `documento_UNIQUE` (`documento` ASC) ,
  INDEX `fk_Cliente_Sucursal1_idx` (`idSucursales` ASC) ,
  CONSTRAINT `fk_Cliente_Sucursal1`
    FOREIGN KEY (`idSucursales`)
    REFERENCES `Banco`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Banco`.`CuentaBancaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco`.`CuentaBancaria` (
  `idcuentaBancaria` INT UNSIGNED NOT NULL,
  `balance` INT NOT NULL,
  `clave` INT NOT NULL,
  `historial` VARCHAR(1000) NOT NULL,
  `cupoPrestamo` INT NOT NULL,
  `deuda` INT NOT NULL,
  `clienteDocumento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcuentaBancaria`),
  UNIQUE INDEX `idcuentaBancaria_UNIQUE` (`idcuentaBancaria` ASC) ,
  INDEX `fk_CuentaBancaria_Cliente_idx` (`clienteDocumento` ASC) ,
  CONSTRAINT `fk_CuentaBancaria_Cliente`
    FOREIGN KEY (`clienteDocumento`)
    REFERENCES `Banco`.`Cliente` (`documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
